# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem 'rails'

gem 'rubocop', '~> 1.13'

gem 'simplecov', '~> 0.21.2'
